name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint • Typecheck • Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TELEMETRY_DISABLED: 1
      # Prevent accidental production secrets usage
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ github.workflow }}-${{ github.job }}-${{ github.ref }}-${{ hashFiles('**/package.json', 'bun.lock') }}
          restore-keys: |
            turbo-${{ github.workflow }}-${{ github.job }}-${{ github.ref }}-
            turbo-${{ github.workflow }}-${{ github.job }}-
            turbo-${{ github.workflow }}-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run check-types

      - name: Build
        run: bun run build

      - name: Upload build artifact (web standalone output)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-standalone
          path: apps/web/.next/standalone
          if-no-files-found: ignore

  tests:
    name: Unit & Component Tests
    runs-on: ubuntu-latest
    needs: build-test
    timeout-minutes: 10
    env:
      TURBO_TELEMETRY_DISABLED: 1
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test:ci

      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: apps/web/coverage
          if-no-files-found: ignore

  # Future jobs: drizzle drift check, security scan, lighthouse, a11y
